"""Command-line interface.

Every subcommand is a thin wrapper over :mod:`elxai.experiments`; the CLI exists
so that a paper table can be regenerated by one documented command instead of a
shell script full of ``--flag`` soup.

Examples
--------
Build the dataset and inspect the split report::

    elxai dataset --config configs/data/belgium.yaml --config configs/split.yaml \
        --set data.extreme.enabled=true

Reproduce the normal-weather comparison (table 3-1)::

    elxai compare --config configs/experiment/normal.yaml \
        --models iTransformer,DLinear,Autoformer,RandomForest

Loss ablation (table 6-1)::

    elxai ablation --config configs/experiment/extreme.yaml \
        --models Autoformer,iTransformer --losses mae,mse,exp

Regenerate a table from existing run directories, without retraining::

    elxai summarize runs/*/  --out results/table3-1.csv
"""

from __future__ import annotations

import argparse
import json
import logging
import sys
from pathlib import Path
from typing import Sequence

from elxai.config import Config, load_composed

log = logging.getLogger("elxai")


def _setup_logging(level: str) -> None:
    logging.basicConfig(
        level=getattr(logging, level.upper(), logging.INFO),
        format="%(asctime)s %(levelname)-7s %(name)s: %(message)s",
        datefmt="%H:%M:%S",
    )


def _load(args: argparse.Namespace) -> Config:
    paths: list[str] = list(args.config or [])
    if not paths:
        raise SystemExit("at least one --config is required")
    return load_composed(paths, overrides=args.set or [])


def _write_table(df, out: str | Path | None, fallback: Path) -> Path:
    import pandas as pd

    target = Path(out) if out else fallback
    target.parent.mkdir(parents=True, exist_ok=True)
    if isinstance(df, pd.DataFrame):
        df.to_csv(target, index=False)
    else:
        target.write_text(json.dumps(df, indent=2, ensure_ascii=False, default=str), encoding="utf-8")
    return target


# --------------------------------------------------------------------------- #
# Subcommands
# --------------------------------------------------------------------------- #


def cmd_dataset(args: argparse.Namespace) -> int:
    from elxai.data import datasets

    cfg = _load(args)
    log.info("config:\n%s", cfg.describe())
    built = datasets.build(cfg)
    out = Path(args.out or (Path(cfg.run.output_dir) / "dataset"))
    datasets.save(built, out)
    summary = built.splits.summary()
    print(summary.to_string(index=False))
    print(f"\nrows={len(built.frame)}  -> {out}")
    if args.check_redistribution:
        from elxai.data.provenance import assert_redistributable

        assert_redistributable(cfg.data.sources)
        print("all sources redistributable")
    return 0


def cmd_train(args: argparse.Namespace) -> int:
    from elxai.experiments import train_one

    cfg = _load(args)
    run = train_one(cfg)
    m = run.result.test_metrics
    print(f"{run.model}: MSE {m.mse:.4f}  MAE {m.mae:.4f}  (n={m.n})")
    print(f"run directory: {run.run_dir}")
    return 0


def cmd_compare(args: argparse.Namespace) -> int:
    from elxai.experiments import run_model_comparison

    cfg = _load(args)
    models = [m.strip() for m in args.models.split(",") if m.strip()]
    table, _ = run_model_comparison(cfg, models)
    print(table.to_string(index=False))
    path = _write_table(
        table, args.out, Path(cfg.run.output_dir) / f"{cfg.experiment}-{cfg.data.name}-comparison.csv"
    )
    print(f"\nwrote {path}")
    return 0


def cmd_ablation(args: argparse.Namespace) -> int:
    from elxai.experiments import run_loss_ablation

    cfg = _load(args)
    losses = [l.strip() for l in args.losses.split(",") if l.strip()]
    models = [m.strip() for m in args.models.split(",")] if args.models else None
    table, _ = run_loss_ablation(cfg, losses, models=models)
    print(table.to_string(index=False))
    path = _write_table(
        table,
        args.out,
        Path(cfg.run.output_dir) / f"{cfg.experiment}-{cfg.data.name}-loss-ablation.csv",
    )
    print(f"\nwrote {path}")
    return 0


def cmd_xai(args: argparse.Namespace) -> int:
    from elxai.experiments import run_xai

    cfg = _load(args)
    cfg.xai.enabled = True
    payload = run_xai(cfg)
    print(json.dumps(payload, indent=2, ensure_ascii=False))
    return 0


def cmd_summarize(args: argparse.Namespace) -> int:
    from elxai.experiments import summarise

    table = summarise(args.runs)
    if table.empty:
        print("no run directories with metrics.json were found", file=sys.stderr)
        return 1
    print(table.to_string(index=False))
    if args.out:
        path = _write_table(table, args.out, Path(args.out))
        print(f"\nwrote {path}")
    return 0


def cmd_config(args: argparse.Namespace) -> int:
    cfg = _load(args)
    print(cfg.describe())
    if args.dump:
        print(json.dumps(cfg.as_dict(), indent=2, ensure_ascii=False, default=str))
    return 0


# --------------------------------------------------------------------------- #
# Parser
# --------------------------------------------------------------------------- #


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(
        prog="elxai",
        description="Electricity load forecasting under normal and extreme weather, with XAI.",
    )
    parser.add_argument("--log-level", default="INFO")
    sub = parser.add_subparsers(dest="command", required=True)

    def add_common(p: argparse.ArgumentParser) -> None:
        p.add_argument(
            "--config",
            action="append",
            required=True,
            help="YAML config; repeat to compose left-to-right",
        )
        p.add_argument(
            "--set",
            action="append",
            metavar="SECTION.FIELD=VALUE",
            help="override a config field, e.g. --set training.loss=exp",
        )

    p = sub.add_parser("dataset", help="build and save the windowed dataset")
    add_common(p)
    p.add_argument("--out", help="output directory")
    p.add_argument(
        "--check-redistribution",
        action="store_true",
        help="refuse to continue if any source may not be redistributed",
    )
    p.set_defaults(func=cmd_dataset)

    p = sub.add_parser("train", help="train and evaluate a single model")
    add_common(p)
    p.set_defaults(func=cmd_train)

    p = sub.add_parser("compare", help="train several models on identical splits")
    add_common(p)
    p.add_argument("--models", required=True, help="comma-separated model names")
    p.add_argument("--out", help="CSV path for the resulting table")
    p.set_defaults(func=cmd_compare)

    p = sub.add_parser("ablation", help="loss-function ablation (paper table 6-1)")
    add_common(p)
    p.add_argument("--losses", required=True, help="comma-separated: mae,mse,exp")
    p.add_argument("--models", help="comma-separated model names (default: config model)")
    p.add_argument("--out", help="CSV path for the resulting table")
    p.set_defaults(func=cmd_ablation)

    p = sub.add_parser("xai", help="train then attribute with SHAP")
    add_common(p)
    p.set_defaults(func=cmd_xai)

    p = sub.add_parser("summarize", help="collect metrics.json from run directories")
    p.add_argument("runs", nargs="+", help="run directories")
    p.add_argument("--out", help="CSV path")
    p.set_defaults(func=cmd_summarize)

    p = sub.add_parser("config", help="print the composed config and its fingerprint")
    add_common(p)
    p.add_argument("--dump", action="store_true", help="also print the full resolved config")
    p.set_defaults(func=cmd_config)

    return parser


def main(argv: Sequence[str] | None = None) -> int:
    parser = build_parser()
    args = parser.parse_args(argv)
    _setup_logging(args.log_level)
    return int(args.func(args))


if __name__ == "__main__":  # pragma: no cover
    raise SystemExit(main())
